Add salmonella cgMLST and serotyping option

diff --git a/jekesa b/jekesa
--- a/jekesa
+++ b/jekesa
@@ -34,9 +34,6 @@ while getopts ":hvp:t:a:s:g" opt; do
     p )
       declare -x project=${OPTARG}
       ;;
-#    f )
-#      declare -x filename=${OPTARG}
-#      ;;
     a )
       declare -x assembler=${OPTARG}
       ;;
@@ -53,6 +50,11 @@ while getopts ":hvp:t:a:s:g" opt; do
       ;;
     g )
       declare -x assemOnly=${OPTARG}
+      if [ $# -lt 4 ]; then
+      echo "Additional arguments missing needed for option: ${OPTARG}"
+      echo "Use [$0 -h] to see full arguments"
+      exit 1
+      fi
       ;;
     h )
       usage
@@ -77,7 +79,7 @@ done
 shift $((OPTIND -1))
 
 # If no parameters are provided, display usage
-if [ -z $project ]; then
+if [ $# -eq 0 ]; then
 	usage
 	exit 1
 fi
@@ -119,21 +121,21 @@ if ! [ -d "$project" ]
       	fi
 fi
 
-
-## databases ##
+#################################################################################
+## 			Set-up paths to databases 			       ##
+#################################################################################
 # ariba reference database
 declare -x ariba_ref=$DATABASES_DIR/ariba_DBs/out.card.prepareref
 declare -x ariba_VFref=$DATABASES_DIR/ariba_DBs/out.vfdb_core.prepareref
 # minikraken database
-#declare -x krakenDB=/media/60tb/src/kraken/NCBI
 declare -x krakenDB=$DATABASES_DIR/kraken_db
 # seroba database
 declare -x db_dir=$DATABASES_DIR/seroba_db
-# PBP typing using CDC Strep Lab scripts and database
-#declare -x allDB_dir=$DATABASES_DIR/SPN_Reference_DB
 # rMLST database
 declare -x confindrDB=$DATABASES_DIR/confindr_db
-
+# resfinder and poinfinder db
+declare -x res_db=$DATABASES_DIR/resfinder_db
+declare -x point_db=$DATABASES_DIR/pointfinder_db
 
 # check if progress file exists
 if [ ! -f $project/progress ]; then
